# Generated by Django 3.1.1 on 2020-09-30 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20200930_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='timeStart',
        ),
        migrations.AddField(
            model_name='event',
            name='timeEnd',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
