# Generated by Django 3.1.5 on 2021-03-25 11:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=20)),
                ('Background_Color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('Font_Color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('Table_Header_Row_Color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('Table_Row_Color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('Table_Row_Alt_Color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
    ]
