# Generated by Django 3.1.5 on 2021-03-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_theme_tabe_border_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='Tabe_Border_Color',
            new_name='Table_Border_Color',
        ),
    ]
