# Generated by Django 3.1.5 on 2021-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210325_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='Page_Header',
            field=models.CharField(default='Header', max_length=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='Page_Subheader_Bottom',
            field=models.CharField(default='Subheader: Bottom', max_length=40),
        ),
        migrations.AddField(
            model_name='theme',
            name='Page_Subheader_Top',
            field=models.CharField(default='Subheader: Top', max_length=40),
        ),
        migrations.AddField(
            model_name='theme',
            name='Page_Title',
            field=models.CharField(default='Title', max_length=30),
        ),
    ]
