# Generated by Django 3.1.5 on 2021-04-08 14:39

import colorfield.fields
from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20210407_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recDate',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Font_Color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Table_Border_Color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
