# Generated by Django 3.1.5 on 2021-04-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0013_auto_20210414_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='recDate',
            field=recurrence.fields.RecurrenceField(verbose_name='date'),
        ),
        migrations.CreateModel(
            name='xtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
