# Generated by Django 3.1.5 on 2021-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_auto_20210414_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.CharField(max_length=20),
        ),
    ]
